### PR TITLE
Task 2 Submission

### PR DESCRIPTION
**Pull request by chttrjeankr**
Task 2 submitted and approved

### CODE REVIEW

**Comment by CheshtaK** [comment]
Hey @chttrjeankr! I see some changes in the Dataset folder too. Remove them and then commit again. Make sure to squash your commits too.

**Comment by chttrjeankr** [comment]
Hey @CheshtaK I added those datasets in the folder to create a reference to the datasets I worked on for the tasks. Are you sure I should remove those?

**Comment by chttrjeankr** [comment]
I assumed all data should be maintained in one folder to keep them organized?

**Comment by CheshtaK** [comment]
The data is accessible by link given in the README. It is always a good thought to keep data organized but I did not add the datasets in the repository to keep it clean and light. 

While it is important to download the datasets to access them in the Jupyter notebook, everyone has a different way of organizing it and while merging PRs this might lead to a number of conflicts. So it's advisable to make changes only in your respective folders.

**Comment by chttrjeankr** [comment]
Makes sense! :+1: Did the necessary amendments.

**Pull request merged**
